### PR TITLE
A Tutorial when starting with a new manifold

### LINKED ISSUE #305: Tutorial when to write an own manifold
In https://github.com/JuliaManifolds/Manifolds.jl/issues/658 we discussed that it might be nice to have a tutorial that continues from https://juliamanifolds.github.io/ManifoldsBase.jl/stable/tutorials/implement-a-manifold/ illustrating which functions should be defined in order for a manifold to be usable with a first optimization algorithm, maybe the gradient descent.

### PR DESCRIPTION
**Pull request by kellertuer**
This is an approach to resolve #305.

Maybe it is also a good idea on this PR to first have a few more “Technical Details” pages per solver similar to https://manoptjl.org/stable/solvers/gradient_descent.html#Technical-Details.

* [x] finished a new tutorial
* [x] introduce vale.sh to reduce errors and formatting in docs – though for now just in md files not yet in doc strings. 
* add “Technical Details” sections to other solvers
  * [x] ARC solver
  * [x] alternating gradient descent
  * [x] ALM
  * [x] Chambolle–Pock
  * [x] CG
  * [x] DoC
  * [x] DouglasRachford
  * [x] EPM
  * [x] gradient descent 
  * [x] Levenbeg–Marquardt
  * [x] Nelder–Mead
  * [x] particle swarm
  * [x] primal dual semi smooth Newton
  * [x] quasi Newton
  * [x] SGD
  * [x] tCG
  * [x] trust regions

### CODE REVIEW

**Comment by kellertuer** [comment]
@blegat before continuing with more technical details sections (they take a bit of time not to miss a function) – can you check whether a tutorial like https://manoptjl.org/previews/PR314/tutorials/ImplementOwnManifold.html is what you would have liked to have?

**Comment by blegat** [comment]
Yes, it's exactly what I had in mind!

**Comment by kellertuer** [comment]
Great! Ten I will carefully add the technical details sections for the other solvers as well; probably also for step sizes and debugs.

**Comment by kellertuer** [comment]
While a few might still be challenging (Chambolle-Pock), I think most (CG, SGD, EPM,...) will just be copies of gradient descent in the technical details. Still good to check them.

And since I am redoing the docs a bit anyways, I will also try to minimise Vale warnings along the way (we at least do not have Vale errors any longer by now).

**Comment by kellertuer** [comment]
I now added a technical section to all solvers that lists (and currently also explains a bit) which functions are required what for. One could maybe shorten that to just listing functions.

Besides that I will maybe wait a day or two whether vale will get Julia code/docstring support and reiterate here again then. If they are not that fast I might just merge this for now.

**Pull request merged**
