### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by hajg-ijk**
This mostly fixes typos and tries to make the spelling of words across files consistent. Concerns tutorial files as well as some files from the documentation folder.

### CODE REVIEW

**Review by kellertuer — COMMENTED** [review]
Super Nice!

1) There seem to be two merge conflict files with the current master (probably they ware changed on master in the mean time since you started collecting these, so if you could locally on your machine get the current master (from here) to be merged into this branch, that would resolve these.

2) Feel free to add yourself in the `.zenodo.json` similar to Constantin (you can add your affiliation and orcid if you like).

**Review by kellertuer — APPROVED** [review]
I'll prove this already, let me know whether you want to add yourself to the zenodo file or not, with that I can merge this :)

**Comment by hajg-ijk** [comment]
Yes actually :) Can I add the edited .json to this PR?

**Comment by kellertuer** [comment]
Sure, it seems you edited the branch here on the server (the commit above is verified, so that indicates it was done on GitHub); so just pull that to your local machine, edit the json and push that again. This PR is linked to the branch, so everything done one the branch shows up in this PR.

**Pull request merged**
