### PR TITLE
Fixes grad_distance functions

### PR DESCRIPTION
**Pull request by hajg-ijk**
Fixes grad_distance functions to make them behave like explained in the docs.

### CODE REVIEW

**Comment by kellertuer** [comment]
Cool. Can you maybe add a test that checks that these new cases (we fixed) are actually doing the correct thing?

**Comment by hajg-ijk** [comment]
I edited the test_gradients.jl file adding test cases for p=1 and x=y and x!=y both for the allocating and the mutating versions. Is this what you meant?

**Comment by kellertuer** [comment]
Yes, that was what I was asking for – as you can see in the report in this PR, the code coverage now covers the new lines (all eight of them). Thanks for adding the tests :) That way we also make sure that we do not accidentally break that later.

**Comment by kellertuer** [comment]
I will merge this already, it will be included in the next release then, but I want to wait for the other bug report just opened this morning and fix that as well in the next version (and also hope we have TagBot back until then).

**Pull request merged**
