### PR TITLE
Add customizable subsolver to trust_regions

### PR DESCRIPTION
**Pull request by mateuszbaran**
This partially solves #240 . Defining custom sub-problems doesn't seem particularly important for extensibility. See also https://discourse.julialang.org/t/ann-manopt-jl/24906/34 .

### CODE REVIEW

**Comment by kellertuer** [comment]
Woah. Superfast. I am just back from touristy things in Bergen.

For the problem – hm – all other solvers habe their own sub problems, so maybe it would be reasonable to come up with the quadratic problem to solver here as well and store that in a sub problem? Maybe that could enable caching at some time or it enables other subsolvers to maybe use more advanced sub problems?
(And I hope it is not too hard to do)

**Comment by mateuszbaran** [comment]
> Woah. Superfast. I am just back from touristy things in Bergen.

Cool, I hope you had fun :slightly_smiling_face: 

> For the problem – hm – all other solvers habe their own sub problems, so maybe it would be reasonable to come up with the quadratic problem to solver here as well and store that in a sub problem? Maybe that could enable caching at some time or it enables other subsolvers to maybe use more advanced sub problems?
> (And I hope it is not too hard to do)

I don't really have a good idea what might be reasonably needed by other subsolvers other than a custom state. I would prefer to go for a simple and minimally breaking solution here but I'm open to specific suggestions :slightly_smiling_face: .

**Comment by kellertuer** [comment]
> Cool, I hope you had fun 🙂
Yeah, I hiked up Ulriken – beautiful view, though from sea level up to 643m height and back is quite a tour.

You might be right, we can switch to a sub problem when necessary as well.
My only concern was that this is the not completely unified, but maybe that is fine until we know for sure what we need here.
Besides that this looks like a much easier fix then I expected ;)

**Review by kellertuer — APPROVED** [review]

**Comment by kellertuer** [comment]
Oh we have to bump version on either this or the other PR.

**Comment by mateuszbaran** [comment]
> Yeah, I hiked up Ulriken – beautiful view, though from sea level up to 643m height and back is quite a tour.

Nice, that's quite high indeed.

> You might be right, we can switch to a sub problem when necessary as well.
> My only concern was that this is the not completely unified, but maybe that is fine until we know for sure what we need here.
> Besides that this looks like a much easier fix then I expected ;)

Yes, it's not completely unified but it goes in the right direction. So there is less work for later :slightly_smiling_face: .

> Oh we have to bump version on either this or the other PR.

I can bump it here.

**Pull request merged**
