### PR TITLE
Allow the CG coefficient β to be complex.

### LINKED ISSUE #201: vector_transport_to function in the grassmann manifolds  doesn't work unless using it with ProjectionTransport()
Hi, I want to use CG-method in grassmann manifolds. but it cannot work, because of the vector_transport_to function of grassmann.
```
M = Grassmann(2, 2, ℂ)
p = rand(M)
X = rand(M; vector_at=p)
q = rand(M)
vector_transport_to(M, p, X, q)
```
error is below.
```
ERROR: MethodError: parallel_transport_to!(::AbstractManifold, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}) is ambiguous. Candidates:
```
this called in  CG-methods (& the others) expects the parallel_transport_to!() for ::AbstractManifold or using it with ProjectionTransport()

### PR DESCRIPTION
**Pull request by kellertuer**
Fixes #201 (the part of that which is Manopt-related).

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I've added a simple test but it doesn't converge to the solution :disappointed: .

**Comment by kellertuer** [comment]
Now this PR even directly resolves the same issue on the limited memory QN code.

**Comment by kellertuer** [comment]
Not yet sure why adding a test reduced the code coverage and one method was not used anymore.

**Review by mateuszbaran — APPROVED** [review]
I think this works fine, and additional improvements to CG can be made separately.

**Pull request merged**
