### PR TITLE
Debug string format

### PR DESCRIPTION
**Pull request by kellertuer**
Start fixing #97 (proposed by @sweichwald .

# Approach

1. Every debug that prints a number gets a format string that is an `printf` style, this is still set to `"$prefix ..." with a reasonable default from before. This way it is backwards compatible.
2. We introduce a new shortcut for the symbol types in the debug array, for example for `:Cost` using `(:Cost, "| %3.4e |") introduces the format (see 1) in the second argument for the `:Cost` debug.
 
The main ones are changed, for the detailed and specific ones, this has still to be done, so this is a draft for now.

### CODE REVIEW

**Comment by kellertuer** [comment]
The main problem seems to be that `@sprintf` can not be used well with non-concrete strings (i.e. if the string is in a variable) and the nicer way (`format`) is not yet available in Julia 1.5. Since I also struggle to get Manopt in Demoed in 1.4 or 1.5 – I might raise the min version – if I do not see good how to format a printf into a string.

**Comment by mateuszbaran** [comment]
I think I'd just bump required version of Julia to 1.6. It's the new LTS so it should be OK. We could drop 1.5 in Manifolds.jl as well.

**Comment by kellertuer** [comment]
Sounds fair with LTS; and this works in 1.6 I checked...

**Comment by kellertuer** [comment]
The main design here is finished – the main (debug options.jl) parts are finished. Now just all dependent and special debugs have to be updated as well to the new signature using `format` instead of `prefix`.

**Comment by kellertuer** [comment]
The special debug prints are still missing, especially the special prints in PrimalDualPlan, that are not just pass-forwards to a field debug print.

**Comment by kellertuer** [comment]
Up to code coverage this should be finished.

**Pull request merged**
